version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alaya
  - apalis
  - direnv
  - dotenv
  - fsrs
  - kwaa
  - moeru
  - msvc
  - nemori
  - nixpkgs
  - pgvector
  - pkgs
  - plast
  - rustc
  - rustls
  - sqlx
  - vchord
  - waifu
ignoreWords: []
import: []
