version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - fsrs
  - kwaa
  - moeru
  - nemori
  - pgvector
  - plast
  - rustls
  - sqlx
  - vchord
  - waifu
ignoreWords: []
import: []
