version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alaya
  - apalis
  - clippy
  - direnv
  - dotenv
  - fsrs
  - iden
  - kwaa
  - moeru
  - msvc
  - nemori
  - nixpkgs
  - paradedb
  - pgvector
  - pkgs
  - pkill
  - plast
  - plastmem
  - pname
  - prefs
  - rustc
  - rustls
  - serde
  - sqlx
  - uuidv
  - vchord
  - waifu
ignoreWords: []
import: []
