services:
  plast-mem:
    image: ghcr.io/moeru-ai/plast-mem:latest
    container_name: plast-mem
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://plastmem:plastmem@localhost/plastmem # TODO: from env
    ports:
      - "3000:3000"
    depends_on:
      - plast-mem-db
